---@alias CameraMode 
---|    `GameCamera.CameraMode.None`--默认模式
---|    `GameCamera.CameraMode.LockLevel`--锁定关卡
---|    `GameCamera.CameraMode.LockRect`--锁定区域
---|    `GameCamera.CameraMode.LockTransform`--跟随单位

---@alias CameraShader
---|    `GameCamera.CameraShader.EarthQuake` -- 抖动
---|    `GameCamera.CameraShader.Manga_Flash_Color` -- 漫画闪光
---|    `GameCamera.CameraShader.Drunk` -- 眩晕
---|    `GameCamera.CameraShader.TV` -- TV
---|    `GameCamera.CameraShader.Pixel` -- 像素化
---|    `GameCamera.CameraShader.Blurry` -- 模糊
---|    `GameCamera.CameraShader.TV50` -- TV50
---|    `GameCamera.CameraShader.TV80` -- TV80
---|    `GameCamera.CameraShader.BluePrint` -- 蓝图
---|    `GameCamera.CameraShader.Comics` -- 漫画
---|    `GameCamera.CameraShader.CompressionFX` -- BUG
---|    `GameCamera.CameraShader.NightVision2` -- 夜视
---|    `GameCamera.CameraShader.Rain_Pro` -- 下雨
---|    `GameCamera.CameraShader.Spot` -- 黑暗
---|    `GameCamera.CameraShader.Grain` -- 颗粒
---|    `GameCamera.CameraShader.Dream2` -- 晃动
---|    `GameCamera.CameraShader.Wave_Horizontal` -- 水中
---|    `GameCamera.CameraShader.Twist` -- 扭曲
---|    `GameCamera.CameraShader.BigFace` -- 放大
---|    `GameCamera.CameraShader.BleachBypass` -- 漂白
---|    `GameCamera.CameraShader.GrayScale` -- 灰度
---|    `GameCamera.CameraShader.Invert` -- 反色
---|    `GameCamera.CameraShader.HSV` -- 颜色调整
---|    `GameCamera.CameraShader.RGB` -- 颜色叠加

---@alias PlaceLayer
---|    `UnitData.PlaceLayer.Unit` -- 单位
---|    `UnitData.PlaceLayer.Decoration` -- 装饰
---|    `UnitData.PlaceLayer.Path` -- 路径
---|    `UnitData.PlaceLayer.Rect` -- 区域
---|    `UnitData.PlaceLayer.Custom` -- 其他
---|    `UnitData.PlaceLayer.Custom2` -- 其他2
---|    `UnitData.PlaceLayer.Custom3` -- 其他3
---|    `UnitData.PlaceLayer.Custom4` -- 其他4
---|    `UnitData.PlaceLayer.Custom5` -- 其他5
---|    `UnitData.PlaceLayer.Player` -- 玩家
---|    `UnitData.PlaceLayer.Monster` -- 怪物

---@alias ControlKey
---|    `ControlKey.None` -- 无按键
---|    `ControlKey.Up` -- 上
---|    `ControlKey.Down` -- 下
---|    `ControlKey.Left` -- 左
---|    `ControlKey.Right` -- 右
---|    `ControlKey.Jump` -- 跳跃
---|    `ControlKey.Item` -- 物品
---|    `ControlKey.Interaction` -- 交互
---|    `ControlKey.Revive` -- 复活
---|    `ControlKey.UseItem` -- 使用物品
---|    `ControlKey.MJump` -- 小跳

---@alias Vector2 UnityEngine.Vector2
---@alias Vector3 UnityEngine.Vector3
---@alias Vector2Int UnityEngine.Vector2Int
---@alias Vector3Int UnityEngine.Vector3Int
---@alias Color UnityEngine.Color
---@alias Sprite UnityEngine.Sprite
---@alias Single number
---@alias Int32 number
---@alias Object nil|boolean|number|string|table|function|userdata|thread