---ic内部函数进度： 10/85

local progress = {
    GameCamera, --OK!
    DamageData,  --OK!
    Data, --OK!
    DataGroup, --OK!
    TimeManager, --OK!
    Game, --OK!
    GameBackground, --OK!
    GamePhysics, --OK!
    GameResourceManager,
    GameWorld,
    Multiplayer,
    AnimationData,
    AudioData,
    CustomFunctionData,
    GameBackgroundData, --OK!
    ItemData,
    ParameterDataArray,
    SkillData,
    TimeLineData,
    TriggerData,
    ColorData,
    UnitData,
    FileManager,
    JFY_CurvilinearMotion,
    JFY_TransitionEffect,
    Level, --OK!
    MusicManager,
    Player,
    PlayerGroup,
    UnitControl,
    ServerData,
    AchievementSystem,
    CharacterString,
    EntitySprite,
    EntityText,
    EnumData,
    ExpressGratitude,
    LuaTool,
    Math,
    ObjectControl,
    ShaderManager,
    SpriteManager,
    Timer,
    XInput,
    TouchInfo,
    XTouch,
    ActionFunction,
    CAManager,
    ConditionFunction,
    ObjectFunction,
    SystemFunction,
    VarManager,
    UI_BarragePanel,
    UI_InfoInputBox,
    UI_SelectBox,
    UI_SelectBoxPanel,
    UI_TimerWindow,
    UI_VirtualKeyManager,
    UI_DialogBox,
    UI_FloatingText,
    UI_InfoBox,
    UI_InfoPanel, --OK!
    ExtendedSetInfoData,
    UI_TextInputBox,
    UI_XEventCallback,
    UI_XImage,
    UI_XMask,
    UI_XRT,
    UI_XTest,
    UI_XUI,
    CharacterUnit,
    MovingUnit,
    PhysicsUnit,
    PlayerUnitX,
    RoleUnit,
    UnitState,
    Unit,
    UnitGroup,
    RaycastHitInfo,
    RaycastParameter,
    GameRoomInfo,
    UI_TextInfo,
    CollisionInfo,
}